name: Notificar a Beamer sobre commit

on:
  push:
    branches:
      - main  # Asegúrate de que tu flujo se ejecute en la rama correcta

jobs:
  notify_beamer:
    runs-on: ubuntu-latest  # El trabajo se ejecutará en un sistema operativo Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Esto hace checkout de tu código

      - name: Obtener información del commit
        id: commit_info
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=%an)" >> $GITHUB_ENV

      - name: Notificar a Beamer
        run: |
          curl -X POST https://api.getbeamer.com/notifications \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.BEAMER_API_TOKEN }}" \
          -d '{
                "title": "Nuevo Commit en Inge3",
                "message": "Se ha realizado un commit en el repositorio Inge3. Commit: '${{ env.COMMIT_HASH }}' - '${{ env.COMMIT_MESSAGE }}'",
                "target_url": "https://app.getbeamer.com/inge3"
              }'
